# This cloudformation stack is manually deployed
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SecretName:
    Type: String
  GoogleClientId:
    Type: String
    NoEcho: true
  GoogleClientSecret:
    Type: String
    NoEcho: true
    
Resources:
  Secret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Ref SecretName
      Description: Secrets
      SecretString: !Sub >-
        {
          "google_client_id":"${GoogleClientId}",
          "google_client_secret":"${GoogleClientSecret}"
        }

Outputs:
  SecretName:
    Description: Secret Name
    Value: !Ref SecretName
